/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.report.campaign.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ABVersion service. Represents a row in the &quot;CT_ABReport_ABVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.content.targeting.report.campaign.newsletter.model.impl.ABVersionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.content.targeting.report.campaign.newsletter.model.impl.ABVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ABVersion
 * @see com.liferay.content.targeting.report.campaign.newsletter.model.impl.ABVersionImpl
 * @see com.liferay.content.targeting.report.campaign.newsletter.model.impl.ABVersionModelImpl
 * @generated
 */
public interface ABVersionModel extends BaseModel<ABVersion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a a b version model instance should use the {@link ABVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this a b version.
	 *
	 * @return the primary key of this a b version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this a b version.
	 *
	 * @param primaryKey the primary key of this a b version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the abversion ID of this a b version.
	 *
	 * @return the abversion ID of this a b version
	 */
	public long getAbversionId();

	/**
	 * Sets the abversion ID of this a b version.
	 *
	 * @param abversionId the abversion ID of this a b version
	 */
	public void setAbversionId(long abversionId);

	/**
	 * Returns the campaign ID of this a b version.
	 *
	 * @return the campaign ID of this a b version
	 */
	public long getCampaignId();

	/**
	 * Sets the campaign ID of this a b version.
	 *
	 * @param campaignId the campaign ID of this a b version
	 */
	public void setCampaignId(long campaignId);

	/**
	 * Returns the alias of this a b version.
	 *
	 * @return the alias of this a b version
	 */
	@AutoEscape
	public String getAlias();

	/**
	 * Sets the alias of this a b version.
	 *
	 * @param alias the alias of this a b version
	 */
	public void setAlias(String alias);

	/**
	 * Returns the views count of this a b version.
	 *
	 * @return the views count of this a b version
	 */
	public int getViewsCount();

	/**
	 * Sets the views count of this a b version.
	 *
	 * @param viewsCount the views count of this a b version
	 */
	public void setViewsCount(int viewsCount);

	/**
	 * Returns the goal count of this a b version.
	 *
	 * @return the goal count of this a b version
	 */
	public int getGoalCount();

	/**
	 * Sets the goal count of this a b version.
	 *
	 * @param goalCount the goal count of this a b version
	 */
	public void setGoalCount(int goalCount);

	/**
	 * Returns the modified date of this a b version.
	 *
	 * @return the modified date of this a b version
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this a b version.
	 *
	 * @param modifiedDate the modified date of this a b version
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ABVersion abVersion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ABVersion> toCacheModel();

	@Override
	public ABVersion toEscapedModel();

	@Override
	public ABVersion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}